---
title: "Crash Data set"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
library(ggplot2)
library(leaflet)
```

```{r}
setwd("C:/Users/ubjho/Downloads")
crash_data <- read_csv("Crash_Drivers.csv")
```

```{r}
head(crash_data)
```

```{r}
colnames(crash_data)
```

### Time format

```{r}
# Extract Year (from text)
crash_data$Year <- as.numeric(substr(crash_data$'Crash Date/Time', 7, 10))
```

```{r}
# Extract Month
crash_data$Month <- as.numeric(substr(crash_data$'Crash Date/Time', 1, 2))
```

```{r}
# Extract Hour (12-hour format)
crash_hour <- as.numeric(substr(crash_data$'Crash Date/Time', 12, 13))
```

```{r}
# Extract AM/PM
am_pm <- substr(crash_data$'Crash Date/Time', 21, 22)
```

```{r}
# Convert to 24-hour format
crash_hour[am_pm == "PM" & crash_hour != 12] <- crash_hour[am_pm == "PM" & crash_hour != 12] + 12
crash_hour[am_pm == "AM" & crash_hour == 12] <- 0
```

```{r}
crash_data$Hour <- crash_hour
```

```{r}
crash_data
```

### Removing columns not in use

```{r}
crash_data$'Person ID' <- NULL
crash_data$'Report Number' <- NULL
crash_data$'Agency Name' <- NULL
crash_data$'Route Type' <- NULL
crash_data$'Cross-Street Name' <- NULL
crash_data$'Off-Road Description' <- NULL
crash_data$'Municipality' <- NULL
crash_data$'Non-Motorist Substance Abuse' <- NULL
crash_data$'Vehicle ID' <- NULL
crash_data$'Location' <- NULL
crash_data$'Parked Vehicle' <- NULL
crash_data$'Vehicle Going Dir' <- NULL
crash_data$'Vehicle Damage Extent' <- NULL
crash_data$'Vehicle First Impact Location' <- NULL

```

```{r}
crash_data
```

### Clean Weather

```{r}
crash_data$Weather <- ifelse(crash_data$Weather %in% c("RAINING", "Rain", "Freezing Rain Or Freezing Drizzle"), "Rain",
                    ifelse(crash_data$Weather %in% c("snow", "SNOW","Blowing Snow", "SLEET", "WINTRY MIX", "BLOWING SNOW", "Sleet Or Hail"), "Snow",
                    ifelse(crash_data$Weather %in% c("Severe Crosswinds", "SEVERE WINDS"), "Windy",
                    ifelse(crash_data$Weather %in% c("BLOWING SAND, SOIL, DIRT","Cloudy", "Fog, Smog, Smoke", "FOGGY", "CLOUDY", "Blowing Sand, Soil, Dirt"), "Cloudy",
                    ifelse(crash_data$Weather %in% c("clear", "CLEAR"), "Clear", crash_data$Weather)))))

crash_data <- filter(crash_data, 
                  !is.na(Weather), Weather != "", 
                  !Weather %in% c("Other", "Unknown", "UNKNOWN", "OTHER", "N/A"))

```

```{r}
unique(crash_data$'Weather')
```

### Clean Light Level

```{r}
crash_data$Light <- gsub(" ", "", crash_data$Light)
```

```{r}
crash_data$Light <- ifelse(crash_data$Light %in% c("DARK--UNKNOWNLIGHTING", "Dark-UnknownLighting", "Dark-NotLighted", "DARKNOLIGHTS"), "Dark",
                    ifelse(crash_data$Light %in% c("Daylight", "DAYLIGHT"), "Daylight",
                    ifelse(crash_data$Light %in% c("Dark-Lighted", "DARKLIGHTSON", "DUSK", "Dusk", "Dawn", "DAWN"), "Medium", crash_data$Light)))

crash_data <- filter(crash_data, 
                  !is.na(Light), Light != "", 
                  !Light %in% c("Other", "Unknown", "UNKNOWN", "OTHER", "N/A"))

```

```{r}
unique(crash_data$Light)
```

### Clean Substance Use

```{r}
crash_data$'Driver Substance Abuse' <- ifelse(crash_data$'Driver Substance Abuse' %in% c("ALCOHOL PRESENT", "ALCOHOL CONTRIBUTED", "Suspect of Alcohol Use, Not Suspect of Drug Use", "Suspect of Alcohol Use, Unknown"), "ALCOHOL PRESENT",
                                              
                    ifelse(crash_data$'Driver Substance Abuse' %in% c("COMBINATION CONTRIBUTED", "COMBINED SUBSTANCE PRESENT", "Suspect of Alcohol Use, Suspect of Drug Use"), "DRUG AND ALCOHOL CONTRIBUTED",
                           
                    ifelse(crash_data$'Driver Substance Abuse' %in% c("ILLEGAL DRUG PRESENT", "ILLEGAL DRUG CONTRIBUTED","MEDICATION CONTRIBUTED", "MEDICATION PRESENT", "Not Suspect of Alcohol Use, Suspect of Drug Use", "Unknown, Suspect of Drug Use"), "DRUG PRESENT",
                    
                           ifelse(crash_data$'Driver Substance Abuse' %in% c("N/A", "Not Suspect of Alcohol Use, Not Suspect of Drug Use", "Unknown, Unknown", "Unknown, Not Suspect of Drug Use", "NONE DETECTED", "UNKNOWN", "Not Suspect of Alcohol Use, Unknown", "OTHER"), "NONE DETECTED" ,crash_data$'Driver Substance Abuse'))))

```

```{r}
unique(crash_data$'Driver Substance Abuse')
```

### Clean Injury Severity

```{r}
crash_data$'Injury Severity' <- ifelse(crash_data$'Injury Severity' %in% c("No Apparent Injury", "NO APPARENT INJURY"), "No Apparent Injury",
                                       
                    ifelse(crash_data$'Injury Severity' %in% c("Possible Injury", "POSSIBLE INJURY", "SUSPECTED MINOR INJURY", "Suspected Minor Injury"), "Possible Minor Injury",
                           
                    ifelse(crash_data$'Injury Severity' %in% c("Suspected Serious Injury", "SUSPECTED SERIOUS INJURY"), "Suspected Serious Injury",
                           
                    ifelse(crash_data$'Injury Severity' %in% c("FATAL INJURY", "Fatal Injury"), "Fatal Injury", crash_data$'Injury Severity'))))

crash_data <- filter(crash_data 
                  [!is.na(crash_data$'Injury Severity'), ], 
                  !'Injury Severity' %in% c("Other", "Unknown", "UNKNOWN", "OTHER"))
```

```{r}
unique(crash_data$'Injury Severity')
```

### Filter 2022 to recent

```{r}
# Filter 2022+
recent_crash <- crash_data[crash_data$Year >= 2022, ]
```

### Keeping only drivers at fault or not

```{r}
cleaned_crash <- recent_crash[recent_crash$'Driver At Fault' != "Unknown", ]
```

```{r}
unique(cleaned_crash$'Driver At Fault')
```

### Remove missing/invalid coordinates

```{r}
cleaned_crash <- cleaned_crash[
  !is.na(cleaned_crash$Latitude) &
  !is.na(cleaned_crash$Longitude) &
  cleaned_crash$Latitude != 0 &
  cleaned_crash$Longitude != 0,
]
```

```{r}
cleaned_crash
```

```{r}
write_csv(cleaned_crash, "clean_crash_JUrquilla.csv")
```
